"""link id on clicks table

Revision ID: ae86671b2e80
Revises: 432196fd4601
Create Date: 2025-02-05 17:23:28.890866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae86671b2e80'
down_revision: Union[str, None] = '432196fd4601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_clicks', sa.Column('link_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'affiliate_clicks', 'affiliate_links', ['link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'affiliate_clicks', type_='foreignkey')
    op.drop_column('affiliate_clicks', 'link_id')
    # ### end Alembic commands ###
